import type { CapabilityPack } from "@open-lagrange/capability-sdk";
import {
  CreateBriefInput,
  CreateBriefOutput,
  CreateSourceSetInput,
  CreateSourceSetOutput,
  ExportMarkdownInput,
  ExportMarkdownOutput,
  ExtractContentInput,
  ExtractContentOutput,
  ExtractSourcesInput,
  ExtractSourcesOutput,
  ResearchPlanSearchInput,
  ResearchPlanSearchOutput,
  ResearchFetchSourceInput,
  ResearchFetchSourceOutput,
  ResearchFetchSourcesInput,
  ResearchFetchSourcesOutput,
  ResearchSearchSourcesInput,
  ResearchSearchSourcesOutput,
  ResearchSearchInput,
  ResearchSearchOutput,
  ResearchSelectSourcesInput,
  ResearchSelectSourcesOutput,
} from "./schemas.js";
import { researchCapability } from "./descriptors.js";
import {
  runResearchCreateBrief,
  runResearchCreateSourceSet,
  runResearchExportMarkdown,
  runResearchExtractContent,
  runResearchExtractSources,
  runResearchFetchSource,
  runResearchFetchSources,
  runResearchPlanSearch,
  runResearchSearch,
  runResearchSearchSources,
  runResearchSelectSources,
} from "./executor.js";
import { researchManifest } from "./manifest.js";

export const researchPack: CapabilityPack = {
  manifest: researchManifest,
  capabilities: [
    researchCapability({
      name: "research.plan_search",
      description: "Create a bounded SearchPlan for provider-backed source discovery.",
      input_schema: ResearchPlanSearchInput,
      output_schema: ResearchPlanSearchOutput,
      side_effect_kind: "none",
      execute: runResearchPlanSearch,
    }),
    researchCapability({
      name: "research.search",
      description: "Search live provider results when configured, or deterministic fixture sources only when fixture mode is explicit.",
      input_schema: ResearchSearchInput,
      output_schema: ResearchSearchOutput,
      side_effect_kind: "none",
      execute: runResearchSearch,
    }),
    researchCapability({
      name: "research.search_sources",
      description: "Execute a bounded SearchPlan through configured search providers and record source candidates.",
      input_schema: ResearchSearchSourcesInput,
      output_schema: ResearchSearchSourcesOutput,
      side_effect_kind: "network_read",
      execute: runResearchSearchSources,
    }),
    researchCapability({
      name: "research.select_sources",
      description: "Select bounded source candidates from a SearchResultSet.",
      input_schema: ResearchSelectSourcesInput,
      output_schema: ResearchSelectSourcesOutput,
      side_effect_kind: "none",
      execute: runResearchSelectSources,
    }),
    researchCapability({
      name: "research.fetch_source",
      description: "Fetch an explicit live URL or an explicitly requested fixture source and record source snapshot artifacts.",
      input_schema: ResearchFetchSourceInput,
      output_schema: ResearchFetchSourceOutput,
      side_effect_kind: "network_read",
      execute: runResearchFetchSource,
    }),
    researchCapability({
      name: "research.fetch_sources",
      description: "Fetch a bounded set of selected source candidates and record source snapshot artifacts.",
      input_schema: ResearchFetchSourcesInput,
      output_schema: ResearchFetchSourcesOutput,
      side_effect_kind: "network_read",
      execute: runResearchFetchSources,
    }),
    researchCapability({
      name: "research.extract_content",
      description: "Extract readable source text and citation metadata from supplied HTML, Markdown, or text.",
      input_schema: ExtractContentInput,
      output_schema: ExtractContentOutput,
      side_effect_kind: "none",
      execute: runResearchExtractContent,
    }),
    researchCapability({
      name: "research.extract_sources",
      description: "Extract readable text and citation metadata from a bounded set of fetched source snapshots.",
      input_schema: ExtractSourcesInput,
      output_schema: ExtractSourcesOutput,
      side_effect_kind: "none",
      execute: runResearchExtractSources,
    }),
    researchCapability({
      name: "research.create_source_set",
      description: "Create a deterministic curated set of extracted sources.",
      input_schema: CreateSourceSetInput,
      output_schema: CreateSourceSetOutput,
      side_effect_kind: "none",
      execute: runResearchCreateSourceSet,
    }),
    researchCapability({
      name: "research.create_brief",
      description: "Use the configured model provider to synthesize a cited Markdown research brief from supplied extracted sources only.",
      input_schema: CreateBriefInput,
      output_schema: CreateBriefOutput,
      side_effect_kind: "none",
      execute: runResearchCreateBrief,
    }),
    researchCapability({
      name: "research.export_markdown",
      description: "Export research Markdown as an indexed artifact.",
      input_schema: ExportMarkdownInput,
      output_schema: ExportMarkdownOutput,
      side_effect_kind: "none",
      execute: runResearchExportMarkdown,
    }),
  ],
};
