import { z } from "zod";

export const ExecutionMode = z.enum(["live", "dry_run", "fixture", "mock", "test"]);

export type ExecutionMode = z.infer<typeof ExecutionMode>;

export function executionModeFromDryRun(input: {
  readonly execution_mode?: ExecutionMode | undefined;
  readonly dry_run?: boolean | undefined;
}): ExecutionMode {
  if (input.execution_mode) return input.execution_mode;
  return input.dry_run ? "dry_run" : "live";
}

export function sourceModeWarning(mode: ExecutionMode): string | undefined {
  if (mode === "fixture") return "Generated from deterministic checked-in sources, not live web results.";
  if (mode === "mock") return "Generated from mocked runtime behavior.";
  if (mode === "dry_run") return "Dry run preview only; no live source work was performed.";
  if (mode === "test") return "Generated by a test harness.";
  return undefined;
}
